version: "3"

networks:
  incredible-squaring-network:
    name: incredible-squaring-network
    driver: bridge

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a
    container_name: anvil
    ports:
      # opening the port so we can easily cast to anvil from localhost
      - "8545:8545"
    # changed entrypoint because the default 'bash -c' entrypoint wasn't working the intended way...
    entrypoint: anvil
    volumes:
      - ./tests/anvil/avs-and-eigenlayer-deployed-anvil-state.json:/root/.anvil/state.json
    command: --host 0.0.0.0 --load-state /root/.anvil/state.json
    networks:
      - incredible-squaring-network
  
  anvil-advance-chain-script:
    image: ghcr.io/foundry-rs/foundry:nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a
    depends_on:
      - anvil
    entrypoint: cast
    command: rpc anvil_mine 100 --rpc-url http://anvil:8545
    networks:
      - incredible-squaring-network

  aggregator:
    image: ghcr.io/layr-labs/incredible-squaring/aggregator/cmd/main.go:latest
    container_name: incredible-squaring-aggregator
    depends_on:
      anvil:
        condition: service_started
      anvil-advance-chain-script:
        condition: service_completed_successfully
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: 
      - --config 
      - config-files/aggregator-docker-compose.yaml
      - --credible-squaring-deployment 
      - contracts/script/output/31337/credible_squaring_avs_deployment_output.json
      - --ecdsa-private-key 
      - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
    networks:
      - incredible-squaring-network

  operator1:
    image: ghcr.io/layr-labs/incredible-squaring/operator/cmd/main.go:latest
    container_name: incredible-squaring-operator1
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      anvil-advance-chain-script:
        condition: service_completed_successfully
    volumes:
      - ./:/incredible-squaring/
    working_dir: /incredible-squaring
    command: --config config-files/operator-docker-compose.anvil.yaml
    networks:
      - incredible-squaring-network

  # operator2:
  #   image: ghcr.io/layr-labs/incredible-squaring/operator/cmd/main.go:latest
  #   container_name: incredible-squaring-operator2
  #   depends_on:
  #     anvil:
  #       condition: service_started
  #   volumes:
  #     - ./:/incredible-squaring/
  #   working_dir: /incredible-squaring
  #   command: --config config-files/operator-docker-compose.anvil.yaml --credible-squaring-deployment contracts/script/output/31337/credible_squaring_avs_deployment_output.json --ecdsa-private-key 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d --bls-private-key 2
  #   networks:
  #     - incredible-squaring-network

